# Generated by Django 3.0.7 on 2020-06-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='Competition logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='Team logos/', verbose_name='Logo'),
        ),
    ]
