# Generated by Django 3.0.7 on 2020-06-24 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0002_auto_20200624_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='thumbnail',
            new_name='comp_logo',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='thumbnail',
            new_name='team_logo',
        ),
    ]
