# Generated by Django 3.0.7 on 2020-06-24 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0003_auto_20200624_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='comp_logo',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_logo',
            new_name='thumbnail',
        ),
    ]
