# Generated by Django 3.0.7 on 2020-06-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0004_auto_20200624_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='thumbnail',
            field=models.ImageField(upload_to='Team logos/', verbose_name='Logo'),
        ),
    ]
