# Generated by Django 3.0.7 on 2020-09-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0005_auto_20200627_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='api_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='api_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='api_id',
            field=models.IntegerField(null=True),
        ),
    ]
