# Generated by Django 3.0.7 on 2020-09-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0006_auto_20200918_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='last_api',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='Not Started', max_length=20),
        ),
    ]
