# Generated by Django 3.0.7 on 2020-09-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0007_auto_20200918_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='last_api',
            field=models.DateTimeField(),
        ),
    ]
