# Generated by Django 3.0.3 on 2020-04-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='percentage',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.CreateModel(
            name='RulePayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.Payout')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.Rule')),
            ],
        ),
    ]
