# Generated by Django 3.0.7 on 2020-07-01 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payout',
            options={'ordering': ('position',)},
        ),
    ]
