# Generated by Django 3.0.3 on 2020-04-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_auto_20200415_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='outpays',
            field=models.ManyToManyField(related_name='outpays', through='rule.RulePayout', to='rule.Payout'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='payouts',
            field=models.ManyToManyField(related_name='payouts', to='rule.Payout'),
        ),
    ]
