# Generated by Django 3.0.3 on 2020-04-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0003_auto_20200415_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='name',
        ),
    ]
