# Generated by Django 3.0.7 on 2020-10-02 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type', models.CharField(
                    choices=[('INC', 'Income'), ('OUT', 'Outgoing'), ('TRI', 'Transfer in'), ('TRO', 'Transfer out')],
                    max_length=3)),
                ('date', models.DateField(default=datetime.datetime(2020, 10, 2, 14, 29, 19, 714330, tzinfo=utc))),
                ('pending', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions',
                                             related_query_name='transaction', to='player.Player')),
                ('transfer_player',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='transfers', related_query_name='transfers', to='player.Player',
                                   verbose_name='Transferred from/to')),
            ],
        ),
    ]
