# Generated by Django 3.0.3 on 2020-04-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rule', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('comp_type', models.CharField(choices=[('Domestic League', 'Domestic League'), ('Domestic Cup', 'Domestic Cup'), ('International Cup', 'International Cup'), ('Domestic Friendly', 'Domestic Friendly'), ('International Friendly', 'International Friendly'), ('International Qualifiers', 'International Qualifiers')], default='Domestic League', max_length=100, verbose_name='Competition Type')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ko_datetime', models.DateTimeField(verbose_name='Kick Off')),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('penalties', models.BooleanField(default=False)),
                ('extra_time', models.BooleanField(default=False)),
                ('postponed', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[('Home90', 'Home win in 90 minutes'), ('Draw90', 'Draw in 90 minutes'), ('Away90', 'Away win in 90 minutes'), ('Home120', 'Home win in Extra Time'), ('Away120', 'Away win in Extra Time'), ('HomePens', 'Home win after Penalties'), ('AwayPens', 'Away win after Penalties'), ('ToPlay', 'Still to be played')], default='ToPlay', max_length=8)),
            ],
            options={
                'verbose_name': 'Match (Result)',
                'verbose_name_plural': 'Matches (Results)',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=3)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('country', models.CharField(max_length=200)),
                ('competitions', models.ManyToManyField(to='gameweek.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField(blank=True, default=0, null=True)),
                ('away_score', models.IntegerField(blank=True, default=0, null=True)),
                ('joker', models.BooleanField(default=False)),
                ('submit_date_time', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameweek.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_name', to='gameweek.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameweek.Competition'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_name', to='gameweek.Team'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prize_pool', models.DecimalField(decimal_places=2, max_digits=10)),
                ('_hidden', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=False)),
                ('matches', models.ManyToManyField(to='gameweek.Match')),
                ('rules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.Rule')),
            ],
        ),
        migrations.CreateModel(
            name='MatchProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Match (Create)',
                'verbose_name_plural': 'Matches (Create)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gameweek.match',),
        ),
    ]
