# Generated by Django 3.0.3 on 2020-04-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gameweek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='accepts_members',
            field=models.BooleanField(default=True, verbose_name='Accepts new members'),
        ),
    ]
