# Generated by Django 3.0.3 on 2020-04-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200414_1543'),
        ('gameweek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
        ),
    ]
