# Generated by Django 3.0.3 on 2020-05-20 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('player', '0001_initial'),
        ('gameweek', '0004_prediction_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='created_leagues', related_query_name='league_creator',
                                    to='player.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='owned_leagues', related_query_name='league_owner',
                                    to='player.Player'),
        ),
    ]
