# Generated by Django 3.0.3 on 2020-04-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameweek', '0004_auto_20200414_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
    ]
