# Generated by Django 3.0.3 on 2020-04-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameweek', '0005_auto_20200414_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='Media/Team logos/', verbose_name='Logo'),
        ),
    ]
