# Generated by Django 3.0.7 on 2020-06-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gameweek', '0005_auto_20200520_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_annual',
            field=models.BooleanField(default=False),
        ),
    ]
