# Generated by Django 3.0.7 on 2020-06-09 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gameweek', '0006_league_is_annual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='is_annual',
            new_name='is_aggregate',
        ),
    ]
