# Generated by Django 3.0.3 on 2020-04-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameweek', '0006_auto_20200415_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='country',
            field=models.CharField(choices=[('ENG', 'England'), ('WOR', 'World'), ('EUR', 'Europe'), ('SCO', 'Scotland'), ('ESP', 'Spain'), ('FRA', 'France'), ('GER', 'Germany')], default='ENG', max_length=100),
        ),
    ]
