# Generated by Django 3.0.3 on 2020-04-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameweek', '0007_auto_20200416_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(choices=[('ENG', 'England'), ('WOR', 'World'), ('EUR', 'Europe'), ('SCO', 'Scotland'), ('ESP', 'Spain'), ('FRA', 'France'), ('GER', 'Germany')], default='ENG', max_length=200),
        ),
    ]
