# Generated by Django 3.0.7 on 2020-06-24 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gameweek', '0007_auto_20200609_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='away_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True,
                                              validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='home_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True,
                                              validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
