# Generated by Django 3.0.3 on 2020-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameweek', '0008_auto_20200416_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='aggregated_games',
            field=models.ManyToManyField(blank=True, null=True, to='gameweek.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='matches',
            field=models.ManyToManyField(blank=True, null=True, to='gameweek.Match'),
        ),
    ]
