# Generated by Django 3.0.7 on 2020-06-27 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gameweek', '0008_auto_20200624_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='away_score',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='home_score',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
