# Generated by Django 3.0.7 on 2020-06-27 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gameweek', '0009_auto_20200627_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='away_score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prediction',
            name='home_score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
