# Generated by Django 3.0.7 on 2020-07-01 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('rule', '0002_auto_20200701_1119'),
        ('gameweek', '0010_auto_20200627_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='rules',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rule.Rule'),
            preserve_default=False,
        ),
    ]
