# Generated by Django 3.0.7 on 2020-07-01 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gameweek', '0012_remove_game_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 16, 20, 36, 24859)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 16, 20, 42, 929253)),
            preserve_default=False,
        ),
    ]
