# Generated by Django 3.0.7 on 2020-09-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gameweek', '0016_prediction_replaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='valid_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=12),
        ),
    ]
